import type { Metadata } from "next";
import { Rouge_Script, Montserrat } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

const rougeScript = Rouge_Script({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-rouge-script",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-montserrat",
});

const fonde = localFont({
  src: "../fonts/fonde.woff",
  display: "swap",
  variable: "--font-fonde",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${fonde.variable} ${montserrat.variable} ${rougeScript.variable}`}
    >
      <body className="antialiased">{children}</body>
    </html>
  );
}
